### ISSUE TITLE
Next update

### ISSUE THREAD

**Issue by JonnyRedHed** [ghostwords/chameleon#26]
Are you still working on this add-on. (Opera/Chrome).  Can you give a status update please.

When will it start blocking the fingerprinting efforts of websites.

**Comment by ghostwords** [comment]
Hello! Chameleon is a WIP research project (not yet meant for everyday browsing) that I haven't updated in a while but might come back to soon. If you are looking for an effective privacy extension now, I recommend either [uBlock Origin](https://github.com/gorhill/uBlock) or [Privacy Badger](https://github.com/EFForg/privacybadgerchrome). uBlock takes care of a huge set of known trackers; Privacy Badger tries to automatically discover trackers as you browse the Web. One of the things Privacy Badger looks for is [canvas fingerprinting, a feature I ported from Chameleon](https://github.com/EFForg/privacybadgerchrome/pull/393).

**Comment by Atavic** [comment]
@ghostwords In the readme.md you should promote users to use Chromium, not the official chrome browser.
