### ISSUE TITLE
[Update] user-agent 

### ISSUE THREAD

**Issue by wolfxana** [ghostwords/chameleon#28]
Hi,
i this extension is obsolete ? i love your work on this , but just wandering if you can update the user-agent 
i did update it as now Chrome ask for it to be unpacked to load it ; just do not see your work go to waste .

**Comment by ghostwords** [comment]
Hello! Chameleon is a WIP research project (not meant for everyday browsing) that I haven't updated in a while. If you are looking for an effective privacy extension now, I recommend [uBlock Origin](https://github.com/gorhill/uBlock) and [Privacy Badger](https://github.com/EFForg/privacybadger) (I work on Privacy Badger). uBlock takes care of a huge set of known trackers; Privacy Badger tries to automatically discover trackers as you browse the Web.
