### ISSUE TITLE
is this project abandoned?

### ISSUE THREAD

**Issue by mailinglists35** [ghostwords/chameleon#29]

**Comment by ghostwords** [comment]
Hi! Chameleon is a WIP research project (not meant for everyday browsing) that I haven't updated in a while. If you are looking for an effective privacy extension now, I recommend [uBlock Origin](https://github.com/gorhill/uBlock) and [Privacy Badger](https://github.com/EFForg/privacybadger) (I work on Privacy Badger). uBlock takes care of a huge set of known trackers; Privacy Badger tries to automatically discover trackers as you browse the Web.

**Comment by mailinglists35** [comment]
I use umatrix + PB + UB but still fail to pass the fingerprinting tests on amiunique.org. chameleon looked promising to solve this :(

**Comment by mailinglists35** [comment]
there is [multiloginapp](https://multiloginapp.com/browser-fingerprinting-surveillance-cant-stop/) (not free) that attempts to feed bogus data to fingerprinters but it seems complicated to use.

**Comment by dimqua** [comment]
>I use umatrix + PB + UB but still fail to pass the fingerprinting tests on amiunique.org. chameleon looked promising to solve this :(

Me too. I'm agree with you. 

AFAIK, [Brave](https://brave.com/) is still using chameleon. But there is no uBlock or Privacy Badger for Brave.
